name: Go Build and Release

on:
  push:
    branches:
      - '**'  # Trigger on push to any branch
      - '!main'
  pull_request:
    branches:
      - main  # Trigger on PR to main
  release:
    types: [created]  # Trigger on release creation

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: Set up Go
        uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2
        with:
          go-version: '1.20'  # Specify the Go version you want to use

      - name: Build
        run: make build

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: Set up Go
        uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492 # v2
        with:
          go-version: '1.23'  # Specify the Go version you want to use

      - name: Build binaries for different OS
        run: |
          mkdir -p release
          GOOS=linux GOARCH=amd64 go build -o release/tf-linux ./main.go
          GOOS=darwin GOARCH=amd64 go build -o release/tf-macos ./main.go
          GOOS=windows GOARCH=amd64 go build -o release/tf.exe ./main.go

      - name: Create Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844 # v1
        with:
          files: |
            release/tf-linux
            release/tf-macos
            release/tf.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}