name: Go Build and Release

on:
  push:
    branches:
      - '**'  # Trigger on push to any branch
  pull_request:
    branches:
      - main  # Trigger on PR to main
  release:
    types: [created]  # Trigger on release creation

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'  # Specify the Go version you want to use

      - name: Build
        run: make build

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'  # Only run on merges to main

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.2''  # Specify the Go version you want to use

      - name: Build binaries for different OS
        run: |
          mkdir -p release
          GOOS=linux GOARCH=amd64 go build -o release/tf-linux ./main.go
          GOOS=darwin GOARCH=amd64 go build -o release/tf-macos ./main.go
          GOOS=windows GOARCH=amd64 go build -o release/tf.exe ./main.go

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/tf-linux
            release/tf-macos
            release/tf.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}